### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by aurel-g** [smthemex/ComfyUI_Demucs#4]
Under Linux in a venv with Python 3.11 and ComfyUI's requirements + requirements.txt installed properly :

```
Launching ComfyUI from: /mnt/comfyui/app


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/mnt/comfyui/app/main.py", line 132, in <module>
    import execution
  File "/mnt/comfyui/app/execution.py", line 13, in <module>
    import nodes
  File "/mnt/comfyui/app/nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "/mnt/comfyui/app/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/mnt/comfyui/app/comfy/sd.py", line 6, in <module>
    from comfy import model_management
  File "/mnt/comfyui/app/comfy/model_management.py", line 145, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/mnt/comfyui/app/comfy/model_management.py", line 114, in get_torch_device
    return torch.device(torch.cuda.current_device())
/mnt/comfyui/app/comfy/model_management.py:114: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  return torch.device(torch.cuda.current_device())
Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.0.1+cu117
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Traceback (most recent call last):
  File "/mnt/comfyui/app/main.py", line 132, in <module>
    import execution
  File "/mnt/comfyui/app/execution.py", line 13, in <module>
    import nodes
  File "/mnt/comfyui/app/nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "/mnt/comfyui/app/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/mnt/comfyui/app/comfy/sd.py", line 10, in <module>
    from .ldm.cascade.stage_c_coder import StageC_coder
  File "/mnt/comfyui/app/comfy/ldm/cascade/stage_c_coder.py", line 19, in <module>
    import torchvision
  File "/mnt/comfyui/env/python3.11/65034a4fa250e283a7146b66c51d4a90/lib/python3.11/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/comfyui/env/python3.11/65034a4fa250e283a7146b66c51d4a90/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 4, in <module>
    import torch._custom_ops
ModuleNotFoundError: No module named 'torch._custom_ops'
```

**Comment by smthemex** [comment]
torchaudio>=0.8,<2.1

**Comment by aurel-g** [comment]
Yes it is installed in my venv.

**Comment by smthemex** [comment]
Or use an older torchvision
